<a href="https://colab.research.google.com/github/VitoriaLeticiaa/AT05-Funcoes/blob/main/Atividade.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [10]:
def calcula_imc(peso=70, altura=1.75):
    return peso / (altura ** 2)

print("IMC calculado:", round(calcula_imc(), 2))

IMC calculado: 22.86


In [13]:
alturas = [45, 23, 67, 12, 11, 89, 23, 41, 50, 62, 78, 34, 56, 19, 72, 88, 11, 90, 39, 65,
           76, 27, 48, 59, 81, 14, 11, 93, 3, 68, 29, 52, 74, 16, 85, 20, 55, 38, 69, 11,
           83, 7, 44, 61, 18, 96, 22, 58, 31, 71, 40, 53, 87, 31]

print('Maior valor:', max(alturas))
print('Menor valor:', min(alturas))
print('Soma de todos os valores:', sum(alturas))
print('Valor absoluto de -25:', abs(-25))
print('Arredondamento de 3.14159 para 2 casas decimais:', round(3.14159, 2))

Maior valor: 96
Menor valor: 3
Soma de todos os valores: 2606
Valor absoluto de -25: 25
Arredondamento de 3.14159 para 2 casas decimais: 3.14


In [14]:
from statistics import mean, median, mode, variance, stdev

print('Média:', mean(alturas))
print('Mediana:', median(alturas))
print('Moda:', mode(alturas))
print('Variância da amostra:', variance(alturas))
print('Desvio padrão da amostra:', stdev(alturas))

Média: 48.25925925925926
Mediana: 49.0
Moda: 11
Variância da amostra: 741.1013277428372
Desvio padrão da amostra: 27.223176297831913


In [15]:
from numpy import random

matriz_float = random.random((5, 10))
print("Matriz 5x10 (float entre 0 e 1):\n", matriz_float)


Matriz 5x10 (float entre 0 e 1):
 [[0.50155149 0.42520159 0.36527369 0.18937284 0.17574838 0.90260703
  0.3672591  0.60355213 0.6604602  0.30947079]
 [0.30005243 0.43706869 0.42293139 0.47912788 0.47610414 0.49063426
  0.76305083 0.18984888 0.54423423 0.86236864]
 [0.01673155 0.45502716 0.46111717 0.26581192 0.76523318 0.79955912
  0.64880905 0.64498336 0.27704981 0.18168291]
 [0.61778674 0.9252857  0.21483183 0.64149355 0.40788977 0.94873158
  0.5015579  0.75040459 0.50252267 0.33249522]
 [0.20666567 0.26699201 0.27539339 0.13064389 0.78637598 0.19794846
  0.4523029  0.73328068 0.52779075 0.88568555]]


In [16]:
matriz_int = random.randint(0, 10, size=(8, 4))
print("Matriz 8x4 (inteiros entre 0 e 9):\n", matriz_int)

Matriz 8x4 (inteiros entre 0 e 9):
 [[1 6 4 0]
 [0 5 0 3]
 [9 3 5 7]
 [2 6 7 3]
 [0 1 6 7]
 [5 2 9 6]
 [3 6 9 3]
 [8 8 1 8]]
